### ISSUE TITLE
Can't run Android once plugin is installed

### ISSUE THREAD

**Issue by ponty7** [Softmotions/nativescript-plugin-google-signin-button#1]
Receiving following error:
`Execution failed for task ':transformClassesWithDexForF0F1F2Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/auth/api/signin/internal/zzm;`

Basically, cloned this project (https://github.com/dgomezs/facebook-login.git), updated dependencies, runs fine. Added this plugin and now getting error above. Saw some posts about needing to update Firebase, when developing via Studio, but not entirely sure Firebase is part of project or how to update. 

Here is my setup:

Windows 10
Node: v6.10.2
Tns: 3.2.0
Android Emulator Target: Android 7.0 (API level 24)

Dependencies:
 Plugin                                                  │ Version │
│ @angular/common                          │ 4.4.3   │
│ @angular/compiler                          │ 4.4.3   │
│ @angular/core                                 │ 4.4.3   │
│ @angular/forms                               │ 4.4.3   │
│ @angular/http                                 │ 4.4.3   │
│ @angular/platform-browser                │ 4.4.3   │
│ @angular/platform-browser-dynamic        │ 4.4.3   │
│ @angular/router                          │ 4.4.3   │
│ nativescript-angular                     │ 4.2.0   │
│ nativescript-localstorage                │ ^1.1.5  │
│ nativescript-plugin-google-signin-button │ ^1.0.5  │
│ nativescript-social-login                │ ^1.7.2  │
│ nativescript-theme-core                  │ ~1.0.4  │
│ reflect-metadata                         │ ~0.1.10 │
│ rxjs                                     │ ~5.4.3  │
│ tns-core-modules                         │ 3.2.0   │
│ tns-platform-declarations                │ ^3.2.0  │
└──────────────────────────────────────────┴─────────┘
Dev Dependencies:
┌───────────────────────────────────┬─────────┐
│ Plugin                            │ Version │
│ babel-traverse                    │ 6.26.0  │
│ babel-types                       │ 6.26.0  │
│ babylon                           │ 6.18.0  │
│ lazy                              │ 1.0.11  │
│ nativescript-dev-android-snapshot │ ^0.*.*  │
│ nativescript-dev-typescript       │ ~0.5.0  │
│ typescript                        │ ~2.5.2  │
│ zone.js                           │ ~0.8.17 │
└───────────────────────────────────┴─────────┘

**Comment by ponty7** [comment]
Reading some other posts:
- removed platform android 
- removed node_modules 
- removed hooks
- made sure no *.gz, *.tar, *.zip files were in node_modules
- tns run android
- Now getting this error:

Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.android.gms.auth.api.signin.internal.zzn conflict: C:\workingDirectory\nativeScript\facebook-login\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.4\jars\classes.jar and C:\workingDirectory\nativeScript\facebook-login\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-auth\8.4.0\jars\classes.jar
        at com.telerik.metadata.ClassRepo.addToCache(ClassRepo.java:21)
        at com.telerik.metadata.Builder.build(Builder.java:38)
        at com.telerik.metadata.Generator.main(Generator.java:44)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_144\bin\java.exe'' finished with non-zero exit value 1

**Comment by ponty7** [comment]
Like error says, conflicting jars, followed these directions and works. Yay.

https://github.com/NathanaelA/nativescript-zxing/issues/4
